name: Build

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'include/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'include/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build --config Release
